/* Generated by Together */

package nc.bs.pfxx;

import java.util.Enumeration;

import javax.servlet.http.HttpServletRequest;

import org.w3c.dom.Element;
import org.w3c.dom.NamedNodeMap;

import nc.bs.framework.common.InvocationInfoProxy;
import nc.bs.framework.common.NCLocator;
import nc.bs.logging.Logger;
import nc.bs.ml.NCLangResOnserver;
import nc.bs.pfxx.xxconfig.FileConfigInfoReadFacade;
import nc.itf.org.IOrgConstBasic;
import nc.itf.org.IOrgMetaDataIDConstBasic;
import nc.pubitf.bd.accessor.GeneralAccessorFactory;
import nc.pubitf.bd.accessor.IGeneralAccessor;
import nc.pubitf.org.IGroupPubService;
import nc.vo.bd.accessor.IBDData;
import nc.vo.jcom.lang.StringUtil;
import nc.vo.jcom.util.UniqueIDGenerator;
import nc.vo.ml.MultiLangContext;
import nc.vo.pfxx.exception.EnvInitException;
import nc.vo.pfxx.exception.FileConfigException;
import nc.vo.pfxx.exception.ISendResult;
import nc.vo.pfxx.exception.PfxxException;
import nc.vo.pfxx.pub.PfxxConstants;
import nc.vo.pfxx.util.PfxxUtils;
import nc.vo.pfxx.xxconfig.RequestParameter;
import nc.vo.pfxx.xxconfig.XChangeConfigInfo;
import nc.vo.pub.BusinessException;

/**
 * 配置信息，参数提取分析类 负责从URL，XML文件提取配置信息
 * 
 * @author cch
 * @modify zhaoxub 2010-05-25 <br>
 *         1)统一使用receiver，不再使用"公司@账簿"格式,也就不需要split,删除以下方法<br>
 *         删除<code>splitReceiver(XChangeConfigInfo xChangeConfigInfo)</code><br>
 *         删除<code>isNeedScheme(XChangeConfigInfo xChangeConfigInfo)</code><br>
 *         删除<code>checkReceiver(String receiver, String[] receiverParts)</code><br>
 *         删除<code>getPKCorp(String receiver)</code><br>
 *         删除<code>checkImportScope(String pk_corp)</code><br>
 *         删除<code>getBdPKByCode(String pk_bdinfo, String docCode)</code><br>
 *         删除<code>getBdPKByPK(String pk_bdinfo, String docPk)</code><br>
 * @modify zhaoxub 2011-01-25 <br>
 *         删除<code>getParameterFromDoc2(Element doc)</code><br>
 *         
 */
public final class ConfigInfoAnalyser
{
    
    /**
     * 合并URL参数和文件头参数，并做简单校验。
     * 
     * @param requestParameter
     * @param docParameter
     * @return
     * @throws EnvInitException
     */
    public static XChangeConfigInfo initConfigInfo(RequestParameter requestParameter, RequestParameter docParameter) throws EnvInitException
    {
        XChangeConfigInfo xChangeConfigInfo = new XChangeConfigInfo();
        
        Logger.info(NCLangResOnserver.getInstance().getStrByID("pfxx", "ConfigInfoAnalyser-0000", null,
            new String[]{requestParameter.getServerURL()})/* 设置服务器的URL:{0} */);
        xChangeConfigInfo.setServerURL(requestParameter.getServerURL());
        
        Logger.info(NCLangResOnserver.getInstance().getStrByID("pfxx",
            "ConfigInfoAnalyser-0001")/* 获取完善配置信息。配置信息的获取优先级顺序为：URL,上传的数据文件头 */);
        String[] fieldNames = docParameter.getAllFieldNames();
        for (String fieldName : fieldNames)
        {
            xChangeConfigInfo.setAttribute(fieldName, docParameter.getAttribute(fieldName));
        }
        
        fieldNames = requestParameter.getAllFieldNames();
        for (String fieldName : fieldNames)
        {
            xChangeConfigInfo.setAttribute(fieldName, requestParameter.getAttribute(fieldName));
        }
        
        String dataSource = null;
        try
        {
            dataSource = PfxxUtils.getDataSourceByAccountCode(xChangeConfigInfo.getAccount());
        }
        catch (PfxxException e)
        {
            throw new EnvInitException(e);
        }
        Logger.info(NCLangResOnserver.getInstance().getStrByID("pfxx", "ConfigInfoAnalyser-0006", null,
            new String[]{dataSource})/* 数据源：{0} */);
        
        // 把数据源绑定到当前线程
        InvocationInfoProxy.getInstance().setUserDataSource(dataSource);
        
        // xChangeConfigInfo.setAttribute(PfxxConstants.LANGCODE,
        // MultiLangContext.getInstance().getCurrentLangVO().getLangcode());
        // 首先绑定主语种，后续出错，多语为主语种
        InvocationInfoProxy.getInstance().setLangCode(MultiLangContext.getInstance().getMainLangVO().getLangcode());
        //
        
        // 如果没有设置replace属性，则使用缺省属性
        String replace = xChangeConfigInfo.getReplace();
        if (StringUtil.isEmpty(replace))
        {
            xChangeConfigInfo.setReplace(PfxxConstants.Y);
        }
        
        Logger.info(NCLangResOnserver.getInstance().getStrByID("pfxx", "ConfigInfoAnalyser-0002", null,
            new String[]{xChangeConfigInfo.getAccount()})/* 获取配置的账套编码:{0} */);
        String account = xChangeConfigInfo.getAccount();
        if (StringUtil.isEmpty(account))
        {
            try
            {
                // 取得系统配置的默认信息
                xChangeConfigInfo.setAccount(FileConfigInfoReadFacade.getGlobalParameter().getDefaultAccount());
                Logger.info(NCLangResOnserver.getInstance().getStrByID("pfxx", "ConfigInfoAnalyser-0003", null,
                    new String[]{xChangeConfigInfo.getAccount()})/* 未取得配置的账套信息，获取默认帐套:{0} */);
            }
            catch (FileConfigException e)
            {
                Logger.error(e.getMessage(), e);
                throw new EnvInitException(e);
            }
        }
        
        // 校验配置信息
        checkConfigInfo(xChangeConfigInfo);
        
        Logger.info(NCLangResOnserver.getInstance().getStrByID("pfxx", "ConfigInfoAnalyser-0004", null,
            new String[]{xChangeConfigInfo.getFileName()})/* 获取配置的文件名:{0} */);
        String fileName = xChangeConfigInfo.getFileName();
        if (StringUtil.isEmpty(fileName))
        {
            // 生成默认的filename
            fileName = UniqueIDGenerator.generate(xChangeConfigInfo.getBillType(), 16, xChangeConfigInfo.getSender(), '0') + ".xml";
            Logger.info(NCLangResOnserver.getInstance().getStrByID("pfxx", "ConfigInfoAnalyser-0005", null,
                new String[]{fileName})/* 文件中未配置文件名称，生成默认文件名:{0} */);
            xChangeConfigInfo.setFileName(fileName);
        }
        
        Logger.info(NCLangResOnserver.getInstance().getStrByID("pfxx",
            "ConfigInfoAnalyser-0007")/* 将sender解析成外系统pk，并检查其合法性 */);
        String pk_exsystem = PfxxUtils.getExsystemPkByCode(xChangeConfigInfo.getSender());
        if (StringUtil.isEmpty(pk_exsystem))
        {
            throw new EnvInitException(ISendResult.ERR_PFXX_SENDER_INVALID,
                xChangeConfigInfo.getSender() + NCLangResOnserver.getInstance().getStrByID("pfxx", "UPPpfxx-000047")
            /*
             * @res "不是一个合法的发送方，请在接收公司注册"
             */);
        }
        xChangeConfigInfo.setPk_exsystem(pk_exsystem);
        
        Logger.info(
            NCLangResOnserver.getInstance().getStrByID("pfxx", "ConfigInfoAnalyser-0008")/* 对集团字段进行翻译... */);
        translateGroup(xChangeConfigInfo);
        
        getGroupNumber(xChangeConfigInfo);
        
        Logger.info(
            NCLangResOnserver.getInstance().getStrByID("pfxx", "ConfigInfoAnalyser-0009")/* 对组织字段进行翻译... */);
        translateOrg(xChangeConfigInfo);
        
        // 把获取的信息赋值给当前的xChangeConfigInfo
        return xChangeConfigInfo;
    }
    
    /**
     * 校验配置信息
     * 
     * @param xChangeConfigInfo
     * @throws EnvInitException
     */
    private static void checkConfigInfo(XChangeConfigInfo xChangeConfigInfo) throws EnvInitException
    {
        // 校验配置信息
        StringBuffer message = new StringBuffer();
        
        // 如果下边信息不满足则不能进行下一步的处理，直接返回。
        String sender = xChangeConfigInfo.getSender();
        if (StringUtil.isEmpty(sender))
        {
            message.append(NCLangResOnserver.getInstance().getStrByID("pfxx", "UPPpfxx-000037")
            /*
             * @res "没有设置sender属性，请在请求的URL中或在发送的文件头的属性中指定sender!"
             */);
        }
        
        String billType = xChangeConfigInfo.getBillType();
        if (StringUtil.isEmpty(billType))
        {
            message.append(NCLangResOnserver.getInstance().getStrByID("pfxx", "UPPpfxx-000038")
            /*
             * @res "没有设置billtype属性，请在请求的URL中或在发送的文件头的属性中指定billtype!"
             */);
        }
        
        if (StringUtil.isEmpty(xChangeConfigInfo.getAccount()))
        {
            message.append(NCLangResOnserver.getInstance().getStrByID("pfxx", "UPPpfxx-000049")
            /*
             * @res "没有设置account属性，请在请求的URL中或在接收方指定缺省account"
             */);
        }
        
        String groupCode = xChangeConfigInfo.getGroupCode();
        if (StringUtil.isEmpty(groupCode))
        {
            message.append(NCLangResOnserver.getInstance().getStrByID("pfxx", "UPPpfxx-000036")
            /*
             * @res "没有设置groupcode属性，请在请求的URL中或在发送的文件头的属性中指定groupcode!"
             */);
        }
        
        // String orgCode = xChangeConfigInfo.getOrgCode();
        // if (StringUtil.isEmpty(orgCode)) {
        // message.append("没有设置orgcode属性，请在请求的URL中或在发送的文件头的属性中指定orgcode!");
        // }
        
        // 处理错误信息
        if (message.toString().trim().length() > 0)
        {
            Logger.error(message.toString());
            throw new EnvInitException(ISendResult.ERR_PFXX_DOCPARA_INVALID, message.toString());
        }
    }
    
    /**
     * 集团翻译
     * 
     * @param xChangeConfigInfo
     * @throws EnvInitException
     */
    private static void translateGroup(XChangeConfigInfo xChangeConfigInfo) throws EnvInitException
    {
        
        // 集团主键查询
        IGeneralAccessor genAcc = GeneralAccessorFactory.getAccessor(IOrgMetaDataIDConstBasic.GROUP);
        IBDData bdData = null;
        if (genAcc != null)
        {
            bdData = genAcc.getDocByCode(IOrgConstBasic.GLOBEORG, xChangeConfigInfo.getGroupCode());
        }
        if (bdData != null && bdData.getPk() != null)
        {
            xChangeConfigInfo.setPk_group(bdData.getPk());
        }
        else
        {
            throw new EnvInitException(ISendResult.ERR_PFXX_RECEIVER_INVALID, nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("pfxx",
                "0pfxx0104")/* @res "不能识别的接收集团编码:" */
                + xChangeConfigInfo.getGroupCode());
        }
    }
    
    private static void getGroupNumber(XChangeConfigInfo xChangeConfigInfo) throws EnvInitException
    {
        try
        {
            String groupNoByPK = NCLocator.getInstance().lookup(IGroupPubService.class).getGroupNoByPK(xChangeConfigInfo.getPk_group());
            xChangeConfigInfo.setGroupno(groupNoByPK);
        }
        catch (BusinessException e)
        {
            Logger.error(e.getMessage(), e);
            throw new EnvInitException(e.getMessage());
        }
    }
    
    /**
     * 组织翻译
     * 
     * @param xChangeConfigInfo
     * @throws EnvInitException
     */
    private static void translateOrg(XChangeConfigInfo xChangeConfigInfo) throws EnvInitException
    {
        
        if (!StringUtil.isEmpty(xChangeConfigInfo.getOrgCode()))
        {
            
            // 按核算账簿查询
            IGeneralAccessor genAcc = null;
            try
            
            {
                genAcc = GeneralAccessorFactory.getAccessor(
                    "fb4da7d4-77b0-4cb8-81c3-db65e32d63af"/* IOrgMetaDataIDConst.ACCOUNTINGBOOK */);
            }
            catch (RuntimeException e)
            {
                Logger.error("can't find ACCOUNTINGBOOK", e);
            }
            IBDData bdData = null;
            if (genAcc != null)
            {
                bdData = genAcc.getDocByCode(xChangeConfigInfo.getPk_group(), xChangeConfigInfo.getOrgCode());
            }
            
            if (bdData == null || bdData.getPk() == null)
            {
                // 按组织查询
                genAcc = GeneralAccessorFactory.getAccessor(IOrgMetaDataIDConstBasic.ORG);
                if (genAcc != null)
                {
                    bdData = genAcc.getDocByCode(xChangeConfigInfo.getPk_group(), xChangeConfigInfo.getOrgCode());
                }
            }
            
            if (bdData == null || bdData.getPk() == null)
            {
                // 按集团查询
                genAcc = GeneralAccessorFactory.getAccessor(IOrgMetaDataIDConstBasic.GROUP);
                if (genAcc != null)
                {
                    bdData = genAcc.getDocByCode(IOrgConstBasic.GLOBEORG, xChangeConfigInfo.getGroupCode());
                }
            }
            
            if (bdData != null && bdData.getPk() != null)
            {
                xChangeConfigInfo.setPk_org(bdData.getPk());
            }
            else
            {
                throw new EnvInitException(ISendResult.ERR_PFXX_RECEIVER_INVALID,
                    NCLangResOnserver.getInstance().getStrByID("pfxx", "ConfigInfoAnalyser-0010", null,
                        new String[]{xChangeConfigInfo.getOrgCode()})/* 不能识别的接收组织编码:{0} */);
            }
        }
    }
    
    /**
     * 通过URL得到相应的参数
     * 
     * @param servletRequest
     * @return RequestParameter
     */
    public static RequestParameter initRequestParameter(HttpServletRequest servletRequest)
    {
        RequestParameter requestParameter = new RequestParameter();
        Enumeration<String> paraNames = servletRequest.getParameterNames();
        while (paraNames.hasMoreElements())
        {
            String paraname = paraNames.nextElement();
            String value = servletRequest.getParameter(paraname);
            requestParameter.setAttribute(paraname, value);
        }
        return requestParameter;
    }
    
    /**
     * 通过XML文档得到相应的参数
     * 
     * @param element
     * @return RequestParameter
     */
    public static RequestParameter getParameterFromDoc(Element element)
    {
        RequestParameter docParameter = new RequestParameter();
        NamedNodeMap attrs = element.getAttributes();
        for (int i = 0; i < attrs.getLength(); i++)
        {
            docParameter.setAttribute(attrs.item(i).getNodeName(), attrs.item(i).getNodeValue());
        }
        // 重新设置处理后得单据类型
        docParameter.setBillType(element.getAttribute(PfxxConstants.BILLTYPE));
        return docParameter;
    }
}
